### ISSUE TITLE
I need help please

### ISSUE THREAD

**Issue by justinjean111** [ibnusyawall/tiktok-downloader#1]
dear Ibnusyawall 
Thanks a lot for your awesome work
I am newbie and I am trying to host this code to my cpanel to test it
I uplaod files to my hosting but it does not work. i seems that there is no index.html for the code to get start showing on browser.
Sure this is a newbie quaestion, if you can help me understand this, I will be very thankful for you

**Comment by ibnusyawall** [comment]
thanks for your first problem, sorry i'm slow to reply to your comment, btw i created this project using laravel but you can't see index.html in the page please add screenshot below so i can help
